services:
  - type: web
    name: biomedica-smarttv
    runtime: node
    rootDir: pagina-web
    buildCommand: npm install && npm run build
    startCommand: npm run serve:prod
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true